// <auto-generated />
using APITodo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APITodo.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221006140526_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("APITodo.Models.Tasks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("date");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_checked");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("task");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("user");

                    b.HasKey("Id");

                    b.ToTable("Todolist");
                });
#pragma warning restore 612, 618
        }
    }
}
